### ISSUE TITLE
AudioDownloader

### ISSUE THREAD

**Issue by rybijakKarpiowy** [GhostMelodyMesh/melody_mesh#5]
- Create an AudioDownloader script, which downloads audio files specified in audioFilesLinks.txt (we can change its name later).
- There must be an option to download only a subset of those files, by providing a number of audio files (optinal) and a seed (optional).
- The program should choose n files, where n is an argument, or some pre-specified constant if null. There should be an option to download all files.
- Those files (or rather, links) should be chosen randomly, with pre-specified random seed. This seed can be changed by an argument.
- Audio downloader should download those files concurrently. It is easily done in python with multiprocessing.Pool.
- The format of audioFilesLinks.txt is to be specified by script creator. You can use any libraries you want, we want to have easy access to large audio databases (for example soundcloud). You may decide to handle a number of websites, from which you download music.
- All audio files should be saved in rawAudio folder.

**Comment by wojciechaniol** [comment]
Currently developed by group "even"
